name: Build and Test MSP430 Project

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: vietduc712/msp430-gcc-9.3.1.11:latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: List files in HOME directory
        run: |
          files=$(ls $HOME)
          echo "Files in $HOME:"
          echo "$files"
  
      - name: Build project
        run: TOOLS_PATH=/home/ubuntu/dev/tools/msp430-gcc make
        working-directory: MSP430_Code

      - name: Run cppcheck
        run: cppcheck src/
        working-directory: MSP430_Code

      - name: Run size check
        run: make size
        working-directory: MSP430_Code

