name: Build and Test MSP430 Project

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: artfulbytes/msp430-gcc-9.3.1.11:latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: List files in HOME directory
        run: |
          files=$(ls $HOME)
          echo "Files in $HOME:"
          echo "$files"

      # - name: List files for debugging
      #   run: ls -al

      # - name: List files in MSP430_Code for debugging
      #   run: ls -al
      #   working-directory: MSP430_Code

      - name: Build project
        run: TOOLS_PATH=/home/ubuntu/dev/tools/msp430-gcc/bin make
        working-directory: MSP430_Code

      - name: Run cppcheck
        run: cppcheck src/
        working-directory: MSP430_Code

      - name: Run tests
        run: make tests
        working-directory: MSP430_Code
